# Generated by Django 3.2.3 on 2021-05-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avator',
            new_name='avatar',
        ),
    ]
